package entity

type BalanceInquiry struct {
	ID             string `json:"accountId,omitempty" bson:"_id,omitempty"`
	MDLUniqueID    string `json:"uniqueId,omitempty" bson:"uniqueId,omitempty"`
	SecretKey      string `json:"-" bson:"secretKey,omitempty"`
	LastBalance    string `json:"-" bson:"lastBalance,omitempty"`
	CurrentBalance int64  `json:"currentBalance" bson:"-"`
	UpdatedAt      int64  `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
}

type BalanceTopUp struct {
	// MongoDB ObjectID
	ID string `json:"accountId,omitempty" bson:"_id,omitempty"`

	// Unique ID yang didapat dari MDL MyDigiLearn yang terdaftar
	MDLUniqueID string `json:"uniqueId,omitempty" bson:"uniqueId,omitempty"`

	// Amount of topup
	Amount int `json:"topupAmount" bson:"topupAmount,omitempty"`

	// Internal Ref Number, generated by system
	InRefNumber string `json:"inRefNumber" bson:"inRefNumber,omitempty"`

	// External Ref Number, generated by third party e.g. SoF
	ExRefNumber string `json:"exRefNumber" bson:"exRefNumber,omitempty"`

	// External Transaction Date / Success Date Time (Topup),
	// generated by third party e.g. SoF
	TransDate int `json:"transDate" bson:"transDate,omitempty"`

	// Balance after addition
	LastBalance int64 `json:"currentBalance,omitempty" bson:"lastBalance,omitempty"`

	// Encrypted last balance after addition
	LastBalanceEncrypted string `json:"-" bson:"-"`

	// Receipt Number
	ReceiptNumber string `json:"receiptNumber,omitempty" bson:"receiptNumber"`

	CreatedAt int64 `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	UpdatedAt int64 `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`

	//SuccessDateTime int    `json:"SuccessDateTime"`
}

type BalanceDeduction struct {
	ID                   string `json:"accountId,omitempty" bson:"_id,omitempty"`
	MDLUniqueID          string `json:"uniqueId," bson:"uniqueId"`
	Amount               int    `json:"amount"`
	MerchantID           int    `json:"merchantID,omitempty"`
	TransType            int    `json:"transType"`
	Description          string `json:"description"`
	InvoiceNumber        string `json:"invoiceNumber"`
	ReceiptNumber        string `json:"receiptNumber,omitempty"`
	LastBalance          int64  `json:"currentBalance,omitempty"`
	LastBalanceEncrypted string `json:"-"`
}
